export default {
    // BASE_URL: "https://sipena.wapfive.com/api",
    BASE_URL: "https://mysekolah.mitraarafah.com/sipena-manpro/api",
    // BASE_URL: "https://0ac7-182-253-116-225.ap.ngrok.io/api",
    BASE_URL_PICTURE: "https://mysekolah.mitraarafah.com/sipena-manpro/",
    TIMEOUT: 10000,
    // EXAMPLE_EMAIL: "siswa",
    // EXAMPLE_PASSWORD: "siswa123",
    // EXAMPLE_EMAIL: "walimuridnonsiswa",
    // EXAMPLE_PASSWORD: "walimuridnonsiswa123",
    // EXAMPLE_EMAIL: "admin",
    // EXAMPLE_PASSWORD: "admin123",
    // EXAMPLE_EMAIL: "tyastok",
    // EXAMPLE_PASSWORD: "tyastok",
    // EXAMPLE_EMAIL: "dinaspendidikan",
    // EXAMPLE_PASSWORD: "dinaspendidikan123",
    EXAMPLE_EMAIL: "kepalasekolah",
    EXAMPLE_PASSWORD: "kepalasekolah123",
    // EXAMPLE_EMAIL: "guru",
    // EXAMPLE_PASSWORD: "guru123",
    // EXAMPLE_EMAIL: "walikelas",
    // EXAMPLE_PASSWORD: "walikelas123",
    // EXAMPLE_EMAIL: "walimuridnew",
    // EXAMPLE_PASSWORD: "walimuridnew123",
    // EXAMPLE_EMAIL: "pegawaikantin",
    // EXAMPLE_PASSWORD: "pegawaikantin123",
    // EXAMPLE_EMAIL: "pegawaikoperasi",
    // EXAMPLE_PASSWORD: "pegawaikoperasi123",
    // EXAMPLE_EMAIL: "pegawai",
    // EXAMPLE_PASSWORD: "pegawai123",
    // EXAMPLE_EMAIL: "pegawaiperpus",
    // EXAMPLE_PASSWORD: "pegawaiperpus123",
    // EXAMPLE_EMAIL: "pengawassekolah",
    // EXAMPLE_PASSWORD: "pengawassekolah123",
    // EXAMPLE_EMAIL: "pegawaitu",
    // EXAMPLE_PASSWORD: "pegawaitu123",
    // EXAMPLE_EMAIL: "pegawaikopsis",
    // EXAMPLE_PASSWORD: "pegawaikopsis123",
    // EXAMPLE_EMAIL: "guruosis",
    // EXAMPLE_PASSWORD: "guruosis123",
    APP_NAME: "Smart School",
    NAME: "Smart School",
}