export default {
    DRAFT: 1,
    MENUNGGU_KONFIRMASI: 2,
    SUDAH_DIKONFIRMASI: 3,
    SEDANG_DIPICKUP: 4,
    BELUM_DPROSES: 5,
    SEDANG_DIPROSES: 6,
    SELESAI_DIPROSES: 7,
    SEDANG_DIKIRIMKAN: 8,
    SELESAI: 9,
    DIBATALKAN: 10,
}